#24 Google calendar event
saigon-tech/chatwork_sgt_bot pull request #26
Opened 2024-10-17 07:40 UTC by tantai1123

2024-10-17 11:30 UTC, huynq2007 requested changes

2024-10-17 11:30 UTC, huynq2007 commented on .env_example
> +MEETING_CALENDAR_ID=
do not use .env for storing sensitive information

2024-10-17 11:30 UTC, huynq2007 commented on src/actions/action_create_meeting_event.py
> +        if os.path.exists("token.json"):
do not use `token.json` for authen as our app server doesn't support persist file system

2024-10-22 02:34 UTC, tantai1123 commented
@huynq2007 
I change to using the google service account
Please confirm!

2024-10-24 07:41 UTC, huynq2007 commented on src/actions/action_create_meeting_event.py
> +        API_URL = self.get_config_value("API_URL")
remove used variable 
API_URL = self.get_config_value("API_URL")
@tantai1123

2024-10-24 07:42 UTC, huynq2007 commented on src/config.py
> +    MEETING_CALENDAR_ID = os.environ.get("MEETING_CALENDAR_ID", "")
@tantai1123 
do not change things outside your action file

2024-10-24 08:53 UTC, huynq2007 approved these changes

2024-10-24 08:53 UTC, merged